spring:
  application:
    name: spring-security-revise
  datasource:
    url: jdbc:postgresql://localhost:5440/todo_app
    username: olmosbek
    password: qwerty123
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8080

security:
  csrf:
    disable: true
  token:
    secret-key: 5533c4c8fa1e89b167eb6c023fe1b6c3fc7d4e0d327c0954aa2ab849a27f9b51
    expiration-period: 86400000
